---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBqLtgi0esCO9HF5mmClTACp55xfgfKmfqX753sX8X/0Fwbok6+Nrx+sq/iWRBssBiTQc6jC7/1/Ztj6sKWwl6tyO+EeKQgRQXeFP4uO03V45cAxdLy21/3UhN6aB48fADY2oMhPo12omJMmAT9zsRkhD5cB6wbmlt8DjFd7JN7RjEyVLo9hjR/Py6/T1k7PbrDzF1QL7/TUd19OUh6AxrAXaF/6PvgX3l6mpmSFhrsGfg2ijdL2IYSou5iGF3x/dUo++jjx288D8k4A/HB9Vh/79QgfreKvLGlnPNpV7p8xlo1JFYwmjpdikaGNU1Cff/MNS7/ds4Px4KZ7j0lyYUSr93QbfMHrHmK1oKw+XVcgLYiz2/82qomRkiYvBek76wqwI13t/GiPjqNvvZBaQ+wdv9KUCcAWN3nortJiSMlqTgrjTMyOiikjVj5+qrgy5CztcUVYqKCPjpbB4OG5kYrVTJG5uy7Q9fMeVCXdGdHwemrNoIgcHjdhrCTlkHZf7FGSv8YZG42apd0gvjwAUNWrvt39963RrPpGMSOx7GAwy3DBi1lG60VyRMNWS5yLzsI+ecX9A7yVKUSfk96Tpb30G3c1N2EyO521T9drWxYodxAK4oeFvk/QOUWBIJDfBaAVjLjFgjyFK79K+9SpqQVhWJ9DFZ750krgmFuiVDkGG/9WkPaZGju/wz+X6dDXA3+uFbPnpxAQTN+qvsI6NHHzsGawp8b5ZYqiAqBvoWTjY+d8vDTtP3DVKtZpcQ5ng38gg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
