---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgA9K3mhObsgC2jwW2VS/Tc7T2TEPQOqDexELh9RQB2elOGtUZdnFjL41bjn1R9QWqiml798bjcM60pYZGrTXEDbX17XFiSR9RAHpskPGY7rkhIzWLrahFKXrG5G37xLjgfPAZ2Jtf2R6m5aszbIpCmRoWGz7gCquMMRkyD92bmcw63UwOOmarBYbeWxQgtnXtMX6Ll2YVUOJjFQJgjdfDbEeMJb/9O+gQlVIpwGhwn+uT5JI/mg/Dk4lZzb+VTgi0hEtosWaneF5xmeaQruc4PZKSieXDhe0Jo7uYfglWBpwQx+3OH34BSx7SlfainvDbNx+nBniUEWpdH/QXcMH8HBZQXxE83DnH0AQoEwS0nA2dGQ5WhOSQSFyx+iV7c3fQgO+gl2j/U/2WvDhcfSDvz5/YimBSaPSdU6k3pYvqjVFdM18gyyOjCBwwllb3cTrjBuNiDuXIrKzDx2/U1+G3xUboLPRJtlSiznXYmkpEi0KOnZgFN2DcdNAws+u0ce6xqiaFoP+sFWWrePaV78vR/BJbrjIEvixTiyU5SgT/RbH16FPt/V5CSur28iur5UkMd9wDmO5iWrdzCc+5gAc0fch7Mbhx6cOyw4UPxp0MYU7X1fAN5VtmUSIMwJQWoMI4np/1GPFGFYc11bLvmc1rkV6w0b7DqgS/wSEV3laAZBgayula29jG0E3miKraY8Mn7Uom8IK4mdeYoKnqN/mqQywFs6DCi04GngnzQi7LKsMmoRiMC9XcTmYoCwsG2/BExQDg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
